#!/bin/bash
# $1 OpenDolphin
# $2 mac-app
# $3... options
#
CONVEYOR=/Applications/Conveyor.app/Contents/MacOS/conveyor
DATE=$(eval date "+%Y%m%d%H%M")

CONVEYOR $3 $4 $5 $6 $7 -Kbuild.date=${DATE} make $2

tar czf ./output/$1-${DATE}.tgz -C ./output $1.app
